
./finalized/central-america-2017.json:
	enveritas-export-dataset \
		--format json \
		--schema-name supplychain \
		--dataset peets-central-america-2017 \
		--outfile ./exports/central-america-2017.json.tmp
	mv ./exports/central-america-2017.json.tmp ./exports/central-america-2017.json
